# Generated by Django 5.2 on 2025-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='label_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='num_annotators',
            field=models.IntegerField(default=1),
        ),
    ]
