# Generated by Django 5.2 on 2025-06-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_instructions_project_label_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='label_schema',
        ),
        migrations.AddField(
            model_name='project',
            name='label_type',
            field=models.CharField(choices=[('SI', 'Single (Radio)'), ('MU', 'Multiple (Checkbox)')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
