# Generated by Django 5.2 on 2025-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataitem', '0002_dataitem_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='dataitem',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
