# Generated by Django 5.2 on 2025-06-16 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_annotation_dataitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='save_finished_annotation',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='text',
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
