# Generated by Django 5.2 on 2025-06-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_remove_annotation_save_finished_annotation_and_more'),
        ('projects', '0003_remove_project_label_schema_project_label_type_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_labels', to='annotation.annotation')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.label')),
            ],
        ),
    ]
