# Generated by Django 5.2 on 2025-06-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_annotationlabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='labels',
        ),
    ]
